//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drogmar_s_Quest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drogmar_s_Quest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blueSpace {
            get {
                object obj = ResourceManager.GetObject("blueSpace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;easyLevel1&gt;
        ///  &lt;walls&gt;
        ///    &lt;x&gt;130&lt;/x&gt;
        ///    &lt;y&gt;24&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/walls&gt;
        ///  &lt;walls&gt;
        ///    &lt;x&gt;172&lt;/x&gt;
        ///    &lt;y&gt;24&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/walls&gt;
        ///  &lt;walls&gt;
        ///    &lt;x&gt;195&lt;/x&gt;
        ///    &lt;y&gt;24&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/walls&gt;
        ///  &lt;walls&gt;
        ///    &lt;x&gt;219&lt;/x&gt;
        ///    &lt;y&gt;24&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/walls&gt;
        ///  &lt;walls&gt;
        ///    &lt;x&gt;243&lt;/x&gt;
        ///    &lt;y&gt;24&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/walls&gt;
        ///  &lt;walls&gt;
        ///    &lt;x&gt;267&lt;/x&gt;
        ///    &lt;y&gt;24&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/walls&gt;
        ///  &lt;walls&gt;
        ///    &lt;x&gt;290&lt;/x&gt;
        ///    &lt;y&gt;24&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EasyLevel1XML {
            get {
                return ResourceManager.GetString("EasyLevel1XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream gameOver {
            get {
                return ResourceManager.GetStream("gameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Jedi_symbol {
            get {
                object obj = ResourceManager.GetObject("Jedi_symbol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream jumpSound {
            get {
                return ResourceManager.GetStream("jumpSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream lifeLost {
            get {
                return ResourceManager.GetStream("lifeLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lightSaber {
            get {
                object obj = ResourceManager.GetObject("lightSaber", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap line_across_black {
            get {
                object obj = ResourceManager.GetObject("line_across_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap line_across_white {
            get {
                object obj = ResourceManager.GetObject("line_across_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mainPlayer {
            get {
                object obj = ResourceManager.GetObject("mainPlayer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menuSpace {
            get {
                object obj = ResourceManager.GetObject("menuSpace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player1 {
            get {
                object obj = ResourceManager.GetObject("Player1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player2 {
            get {
                object obj = ResourceManager.GetObject("Player2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player3 {
            get {
                object obj = ResourceManager.GetObject("Player3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player4 {
            get {
                object obj = ResourceManager.GetObject("Player4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player5 {
            get {
                object obj = ResourceManager.GetObject("Player5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redSpace {
            get {
                object obj = ResourceManager.GetObject("redSpace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap straight_line_black {
            get {
                object obj = ResourceManager.GetObject("straight_line_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap straight_line_white {
            get {
                object obj = ResourceManager.GetObject("straight_line_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;easyLevel1&gt;
        ///  &lt;walls&gt;
        ///    &lt;x&gt;130&lt;/x&gt;
        ///    &lt;y&gt;24&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/walls&gt;
        ///  &lt;walls&gt;
        ///    &lt;x&gt;172&lt;/x&gt;
        ///    &lt;y&gt;24&lt;/y&gt;
        ///    &lt;hp&gt;1&lt;/hp&gt;
        ///  &lt;/walls&gt;
        ///&lt;/easyLevel1&gt;.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upgrade {
            get {
                object obj = ResourceManager.GetObject("upgrade", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yellowSpace {
            get {
                object obj = ResourceManager.GetObject("yellowSpace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
